language: ruby
rvm:
  - 1.9.3
before_script:
  - mysql -e 'create database chatroom_test;'
  - "bundle exec rake db:migrate"
  - "export DISPLAY=:99.0"
  - "chmod -x ./script/ci/run_test.sh"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


script: ./script/ci/run_test.sh
